Parameters:
  DemoInstanceType:
    Description: EC2 Instance Type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
    ConstraintDescription: Choose a Valid EC2 instance Type from the available options.

  SGDescription:
    Description: This is SG group description
    Type: String
  
  SGPort:
    #The description below is the description of the parameter itself
    Description: Security Groups port to open (Must be a single port between 1150-65535)
    #When the CF Template is run, it will prompt for a number
    Type: Number
    MinValue: 1150
    MaxValue: 65535
  
  InboundCIDR:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    #Below is a regex that requires three digits, then a period, etc...
    #This forces the IP range to be configured properly
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  
  MyVPC:
    Description: VPC to operate in
    #In the console, you will click on one of your VPCs
    Type: AWS::EC2::VPC::Id

Resources:
  DemoServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref DemoInstanceType
      ImageId: ami-0a695f0d95cefc163
      SecurityGroups:
        - !Ref demoServerSG
        - !Ref demoServertwoSG
  demoServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SGDescription
      SecurityGroupIngress:
        - CidrIp: !Ref InboundCIDR
          FromPort: !Ref SGPort
          ToPort: !Ref SGPort
          IpProtocol: tcp

  demoServertwoSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SGDescription
      VpcId: !Ref MyVPC