AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to stop EC2 instances daily using Lambda and EventBridge.

Resources:
  # Create the IAM Role for Lambda with EC2 permissions
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'

  # Create the Lambda function to stop EC2 instances
  HelloWorldLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'HelloWorld'
      Runtime: 'python3.9'
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: 'index.lambda_handler'
      Code:
        ZipFile: |
          import boto3

          def lambda_handler(event, context):
              # List the regions where you have EC2 instances
              print("Hello World!")
