AWSTemplateFormatVersion: 2010-09-09
Description: AWS Class - Deploying my first instance through CloudFormation Templates

Resources:
  MyEC2InstanceDay3:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-053b0d53c279acc90
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: aws-class-day3