AWSTemplateFormatVersion: 2010-09-09
Description: AWS Class - Creating VPC, Subnetes, Route Tables, NAT Gateway, EIP, and Internet Gateway 
  Using the Cloud Formation Template

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: MyVPC-DemoClass
        - Key: Day
          Value: Day8