---
- name: Launch EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    instance_name: "FromAnsible"
    instance_type: "t2.micro"
    image_id: "ami-053b0d53c279acc90"
    region: "us-east-1"

  tasks:
    - name: Launch EC2 Instance
      community.aws.ec2_instance:
        instance_type: "{{ instance_type }}"
        image: 
          id: "{{ image_id }}"
        wait: yes
        tags:
          Name: "{{ instance_name }}"
        region: "{{ region }}"
        count: 1
      register: ec2_instance