AWSTemplateFormatVersion: 2010-09-09
Description: AWS EC2 Instance - Deploying through CloudFormation Templates

Resources:
  EC2FromCFT:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-053b0d53c279acc90 # The ID of the AMI. An AMI ID is required to launch an instance and must be specified here or in a launch template.
      InstanceType: t2.micro  # The instance type.
      Tags:
        - Key: Name
          Value: From-CFT