Resources:
  #creating an ec2 instance
  DemoInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-2a
      ImageId: ami-0a695f0d95cefc163
      InstanceType: t2.micro
      #referencing the security group which is created below
      SecurityGroups:
        - !Ref DemoInstanceSecurityGrtoup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install httpd -y
          systemctl enable httpd.service
          systemctl start httpd.service
      #IamInstanceProfile: S3FullAccessEC2
  
  # Assigining EIP to the server
  DemoInstanceEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref DemoInstance

  #Creating Security group with soem inbound rules like 22, 80, and 443 ports
  DemoInstanceSecurityGrtoup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH, HTTP, and HTTPs
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 443
        ToPort: 443