Parameters:

#This is referenced in the EC2 resource below
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    #These four options will be displayed when we run the CF template
    #If you are using automation, make sure to use an allowed value
    AllowedValues:
      - t2.micro
      - t2.small
      - t3.micro
      - t3.small
    ConstraintDescription: Choose a valid EC2 instance type.

  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
#Create an EC2 instance using the parameters above.
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      #References the InstanceType parameter above
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
