Parameters:
#Number Parameter with minimum and maximum
#Used to configure a single port for the SG below
  SecurityGroupPort:
    #The description below is the description of the parameter itself
    Description: Security Groups port to open (Must be a single port between 1150-65535)
    #When the CF Template is run, it will prompt for a number
    Type: Number
    MinValue: 1150
    MaxValue: 65535

#Simple String Parameter
#This is referenced in the SG Below
  SGDescription:
    Description: Security Group Description
    Type: String

#This parameter will take a string, but will not show what you type (NoEcho)
#This paramter is not used below
  DBPwd:
    NoEcho: true
    Description: The database admin account password
    Type: String
    MinLength: 1
    MaxLength: 41
    AllowedPattern: ^[a-zA-Z0-9]*$
    #String Parameter with allowed values

#This is referenced in the EC2 resource below
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    #These four options will be displayed when we run the CF template
    #If you are using automation, make sure to use an allowed value
    AllowedValues:
      - t2.micro
      - t2.small
      - t3.micro
      - t3.small
    ConstraintDescription: Choose a valid EC2 instance type.

#String Parameter with an allowed pattern
#Used to configure incoming CIDRs for one SG below
  AllowedInboundCIDR:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    #Below is a regex that requires three digits, then a period, etc...
    #This forces the IP range to be configured properly
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

#Used to define the VPC that SG and Subnets are in
  MyVPC:
    Description: VPC to operate in
    #In the console, you will click on one of your VPCs
    Type: AWS::EC2::VPC::Id

#Comma delimited list of CIDR ranges for subnets
  SubnetCIDRs:
    Description: "Comma-delimited list of two CIDR blocks"
    Type: CommaDelimitedList
    Default: "10.1.1.0/24, 10.1.2.0/24"

Resources:
#Create an EC2 instance using the instance type parameter.
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      #References the InstanceType parameter above
      InstanceType: !Ref InstanceType
      ImageId: ami-0742b4e673072066f
      #References subnet1 below. Not a parameter
      SubnetId: !Ref Subnet1

#Create a security group using multiple inputs from parameters
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SGDescription
      #The three references below are all parameters above
      SecurityGroupIngress:
        - CidrIp: !Ref AllowedInboundCIDR
          FromPort: !Ref SecurityGroupPort
          ToPort: !Ref SecurityGroupPort
          IpProtocol: tcp
      VpcId: !Ref MyVPC

#Create subnets in the VPC specified by a parameter
  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      #This Select function chooses the first CIDR in the comma delimited list
      CidrBlock: !Select [0, !Ref SubnetCIDRs]

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      #This Select function chooses the second CIDR in the comma delimited list
      CidrBlock: !Select [1, !Ref SubnetCIDRs]
