Resources:
# Create an EC2 instance
  WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0022f774911c1d690
      InstanceType: t2.micro
      #References a SG created below
      SecurityGroups:
        - !Ref DemoSecurityGroup
      #Performs an update and creates a web server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install httpd -y
          systemctl enable httpd.service
          systemctl start httpd.service
      IamInstanceProfile: S3FullAccessEC2

  # Assign an EIP to the Web Server
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref WebInstance

  # Web Server Security Group: 443, 22, 80
  DemoSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH, HTTP, and HTTPs
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        IpProtocol: tcp
        FromPort: 443
        ToPort: 443
